name: autofix.ci # needed to securely identify the workflow

on:
  pull_request:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - run: corepack enable
      - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6
        with:
          node-version: lts/*
          cache: "pnpm"
      - run: pnpm install
      - name: Fix lint issues
        run: pnpm run fmt
      - uses: autofix-ci/action@635ffb0c9798bd160680f18fd73371e355b85f27
        with:
          commit-message: "chore: apply automated lint fixes"
